import React from 'react';
import { Metadata } from 'next';
import Dashboard from './Dashboard';
export const metadata: Metadata = {
    title: "Список",
    description: "Generated by create next app",
  };

  interface pageProps {
    params: Promise<{id : string}>
  }

const DashboardPage : React.FC<pageProps> = async ({
    params
}) => {
        return (
        <>
            <Dashboard
                id={(await params).id}
            />
        </>
    );
}

export default DashboardPage;
