import React from 'react';
import Users from './Users';
import { Metadata } from 'next';
import { getIsAuth } from '@/utils/isAuth';
import { redirect } from 'next/navigation';

export const metadata: Metadata = {
    title: "Список",
    description: "Generated by create next app",
  };

const Page = async () => {
    const isAuth = await getIsAuth()
    if (!isAuth) {
        redirect('/auth')
    }
    return (
        <Users
        />
    );
}

export default Page;
