import React from 'react';
import Users from './Users';
import { Metadata } from 'next';

export const metadata: Metadata = {
    title: "Список",
    description: "Generated by create next app",
  };

const Page = async () => {
    return (
        <Users
        />
    );
}

export default Page;
