import React from 'react';
import Auth from './Auth';
import { Metadata } from 'next';
import { login } from '@/authLib';

export const metadata: Metadata = {
    title: "Страница входа",
    description: "Generated by create next app",
  };

const AuthPage = () => {
    const loginLib = login
    return (
        <>
            <Auth
                loginLib={loginLib}
            />
        </>
    );
}

export default AuthPage;
