import React from 'react';
import Auth from './Auth';
import { Metadata } from 'next';


export const metadata: Metadata = {
    title: "Страница входа",
    description: "Generated by create next app",
};

export const AuthPage = async () => {
    return (
        <>
            <Auth/>
        </>
    );
}

export default AuthPage;
