import React from 'react';
import Auth from './Auth';
import { Metadata } from 'next';
import { login } from '@/authLib';
import { getIsAuth } from '@/utils/isAuth';
import { redirect } from 'next/navigation';

export const metadata: Metadata = {
    title: "Страница входа",
    description: "Generated by create next app",
};

export const AuthPage = async () => {
    const isAuth = await getIsAuth()
    if (isAuth) {
        redirect('/dashboard')
    }
    return (
        <>
            <Auth
                loginLib={login}
            />
        </>
    );
}

export default AuthPage;
