import React from 'react';
import CurrentUser from './CurrentUser';
import { Metadata } from 'next';

export const metadata: Metadata = {
    title: "Список",
    description: "Generated by create next app",
  };

const Page = async () => {
    return (
        <main className='main'>
            <CurrentUser
            />
        </main>
    );
}

export default Page;
