import React from 'react';
import { Metadata } from 'next';
import Dashboard from './Dashboard';
import { getIsAuth } from '@/utils/isAuth';
import { redirect } from 'next/navigation';

export const metadata: Metadata = {
    title: "Список",
    description: "Generated by create next app",
  };

const DashboardPage = async () => {
    const isAuth = await getIsAuth()
    if (!isAuth) {
        redirect('/auth')
    }
    return (
        <>
            <Dashboard
                isLogin={isAuth}
            />
        </>
    );
}

export default DashboardPage;
